### ISSUE TITLE
Bulk Syncing bug

### ISSUE THREAD

**Issue by coaten** [kp4coder/sync-post-with-other-site#1]
We encountered an issue that, when multiple sync targets are selected, only the first in the list is actually synced to. We have identified a solution as follows:

In this file the following function appears to have an error: includes\sps_sync.class.php

```
        function sps_send_data_to( $action, $args = array(), $sps_website = array() ) {
            global $wpdb, $sps, $sps_settings, $post_old_title;
            $general_option = $sps_settings->sps_get_settings_func();

            if( !empty( $general_option ) && isset( $general_option['sps_host_name'] ) && !empty( $general_option['sps_host_name'] ) ) {
                foreach ($general_option['sps_host_name'] as $sps_key => $sps_value) { 

                    $args['sps']['roles'] = isset( $general_option['sps_roles_allowed'][$sps_key]['roles'] ) ? $general_option['sps_roles_allowed'][$sps_key]['roles'] : array();
                    $args['sps']['host_name']   = !empty( $sps_value ) ? $sps_value : '';
                    $args['sps']['strict_mode'] = isset( $general_option['sps_strict_mode'][$sps_key] ) ? $general_option['sps_strict_mode'][$sps_key] : 1;
                    $args['sps']['roles']['administrator'] = 'on';

                    $args['sps']['content_match'] = isset( $general_option['sps_content_match'][$sps_key] ) ? $general_option['sps_content_match'][$sps_key] : 'title';
                    $args['sps']['content_username'] = isset( $general_option['sps_content_username'][$sps_key] ) ? $general_option['sps_content_username'][$sps_key] : '';
                    $args['sps']['content_password'] = isset( $general_option['sps_content_password'][$sps_key] ) ? $general_option['sps_content_password'][$sps_key] : '';

                    if( isset($args['post_content']) && isset($args['sps']['strict_mode']) && $args['sps']['strict_mode'] ) {
                        $args['post_content'] = addslashes($args['post_content']);
                    } else {
                        $args['post_content'] = do_shortcode($args['post_content']);
                    }

                    $loggedin_user_role = wp_get_current_user();
                    $matched_role = array_intersect( $loggedin_user_role->roles, array_keys( $args['sps']['roles'] ) );

                    if( !empty($sps_value) && !empty($matched_role) && in_array($sps_value, $sps_website) ) {
                        return $this->sps_remote_post( $action, $args );
                    }
                }
            }
        }
```
At the end of this function, the line "return $this->sps_remote_post( $action, $args );" is within the foreach loop that iterates through all target sites to be synced to. This results in ending the foreach loop before the post is synced to the second (or more) selected sites.

Our solution to this is to remove the "return " statement before "$this->sps_remote_post( $action, $args );" then replace the following code in the sps_save_post() function to account for lack of return value from sps_send_data_to() as follows:
Current Code:
```
                $response = $this->sps_send_data_to( 'add_update_post', $args, $sps_website );

                if( is_array($response) ) {
                    if( isset( $response['response']['code'] ) && $response['response']['code'] == 200 ) {
                        $other_site_post_id = $response['body'];
                    }
                }
```
Replacement code:
```
$this->sps_send_data_to( 'add_update_post', $args, $sps_website );
```

Nothing is actually done with $response, nor $other_site_post_id anyway.

**Comment by kp4coder** [comment]
Thank you for taking the time to report the issue with my plugin and for providing a solution. I truly appreciate your contribution to improving the plugin.

I'll review the solution you provided and integrate it into the next update. If you have any other suggestions or encounter any further issues, please feel free to reach out.

Thanks again for your support!

**Comment by kp4coder** [comment]
Thank you for taking the time to report the issue with my plugin and for providing a solution. I truly appreciate your contribution to improving the plugin.

I'll review the solution you provided and integrate it into the next update. If you have any other suggestions or encounter any further issues, please feel free to reach out.

Thanks again for your support!
